# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' decode_line_cpp
#' @description
#' decode line return from ggmap::route(from, to, output = "all")
#' useful when draw route on map so route will follow real route.
#' @export
decode_line_cpp <- function(encoded) {
    .Call('route_decode_line_cpp', PACKAGE = 'route', encoded)
}

